name: Publish packages to the Maven Central Repository
on:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.352'
          distribution: 'temurin'
          cache: 'maven'
          server-id: 'ossrh'
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish packages
        run: mvn -U -B clean deploy -P release
